name: tpwriter
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - nb_conda_kernels
  - pip:
    - torchviz